implemented base structure and some tests with date and time
trainitek/backtothefuture pull request #1
Opened 2023-10-15 09:49 UTC by marekdominiak

2023-10-18 12:51 UTC, vprudnikov requested changes

2023-10-18 12:51 UTC, vprudnikov commented on src/main/java/com/trainitek/backtothefuture/application/CompleteEnrollmentHandler.java
> +        Enrollment enrollment = repository.findById(enrollmentId)
use `var`, it's a modern way of writing the code :)
The comment refers to all the places.

2023-10-18 12:51 UTC, vprudnikov commented on src/main/java/com/trainitek/backtothefuture/application/CompleteEnrollmentHandler.java
> +                .orElseThrow(() -> new IllegalArgumentException("Enrollment id=%s not found".formatted(enrollmentId)));
maybe IllegalArgumentException is not the best choice

2023-10-18 12:51 UTC, vprudnikov commented on src/main/java/com/trainitek/backtothefuture/domain/Enrollment.java
> +    public static Enrollment completedEnrollment(@NonNull User student, @NonNull User enroller, @NonNull Course course,
why may we have a started and completed enrollment in the production code?

2023-10-18 12:51 UTC, vprudnikov commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +    def "Enrollment should fail if enrolledAt is after as availableFrom"() {
I have a question about it in Slack. So if it answered, then this comment can be just resolved

2023-10-18 12:51 UTC, vprudnikov commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +    def "Started enrollment can completed"() {
```suggestion
    def "Started enrollment can be completed"() {
```

2023-10-18 12:51 UTC, vprudnikov commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +    def "Enrollment should not start if started too early"() {
```suggestion
    def "Enrollment cannot be started too early"() {
```

2023-10-18 12:51 UTC, vprudnikov commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +    def "Enrollment should succeed if enrolledAt is before or equal as availableFrom"() {
too technical summary, imho

2023-10-18 12:51 UTC, vprudnikov commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +        def expectedValidUntilDate = clock.instant().atZone(zone)
maybe it was hard to implement it, however, I wouldn't show this to the audience since this line, most probably, repeats the production code. Instead, there should be specific dates, not calculations.

2023-10-18 12:51 UTC, vprudnikov commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +    def "Started enrollment can't be completed if time was tampered with"() {
maybe it was me, but it was a bit hard to understand: why would we go back in time?

2023-10-18 12:51 UTC, vprudnikov commented on src/test/java/com/trainitek/backtothefuture/config/MutableClockTestExecutionListener.java
> +        mutableClock.setInstant(Clock.systemDefaultZone().instant());
that was surprising... so we need to reset it each time? Doesn't Spock do that? If not, I need to fix my code then =)

2023-10-18 15:43 UTC, marekdominiak commented on src/main/java/com/trainitek/backtothefuture/application/CompleteEnrollmentHandler.java
> +        Enrollment enrollment = repository.findById(enrollmentId)
OK

2023-10-18 15:44 UTC, marekdominiak commented on src/main/java/com/trainitek/backtothefuture/domain/Enrollment.java
> +    public static Enrollment completedEnrollment(@NonNull User student, @NonNull User enroller, @NonNull Course course,
(could be - historical enrollments)

2023-10-18 15:51 UTC, marekdominiak commented on src/test/java/com/trainitek/backtothefuture/config/MutableClockTestExecutionListener.java
> +        mutableClock.setInstant(Clock.systemDefaultZone().instant());
This is for Spring, so I can't see how we would have a new MutableClock (which is a singleton cleared) without TestExecutionListener. For unit tests, we can replace it, but for integration.

I have checked it, and without the Cleanup this won't work in Java. (in spock without 


```    def setup() {
        // reset the Clock after each test
        // in a real project we could create a Spring TestExecutionListener in order to do that
        clock.setInstant(Instant.now().atZone(ZoneId.of("UTC")).toInstant())
    } ``` in IntegrationClockSupport it won't work (or without the testExecutionListener)

2023-10-19 04:49 UTC, marekdominiak commented on src/main/java/com/trainitek/backtothefuture/application/CompleteEnrollmentHandler.java
> +                .orElseThrow(() -> new IllegalArgumentException("Enrollment id=%s not found".formatted(enrollmentId)));
What would you suggest?

2023-10-19 12:29 UTC, marekdominiak commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +    def "Enrollment should fail if enrolledAt is after as availableFrom"() {
@vprudnikov Answered on slack

2023-10-19 19:52 UTC, vprudnikov requested changes

2023-10-19 19:52 UTC, vprudnikov commented on src/main/java/com/trainitek/backtothefuture/application/CompleteEnrollmentHandler.java
> +                .orElseThrow(() -> new IllegalArgumentException("Enrollment id=%s not found".formatted(enrollmentId)));
`EntityNotFoundException`?

2023-10-19 19:52 UTC, vprudnikov commented on src/main/java/com/trainitek/backtothefuture/domain/Enrollment.java
> +    public static Enrollment completedEnrollment(@NonNull User student, @NonNull User enroller, @NonNull Course course,
it looks like this is because you need them in the tests. But maybe I missed the point.

2023-10-19 19:52 UTC, vprudnikov commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +        def startedAt = availableFrom
```suggestion
        def startedAt = date("2023-09-11")
        def enrolledAt = startedAt 
        def availableFrom = startedAt 
```

2023-10-19 19:52 UTC, vprudnikov commented on src/test/java/com/trainitek/backtothefuture/config/MutableClockTestExecutionListener.java
> +        mutableClock.setInstant(Clock.systemDefaultZone().instant());
I have added a task for myself to fix it

2023-10-19 19:52 UTC, vprudnikov commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +        thrown(IllegalArgumentException)
maybe you forgot to check the details

2023-10-20 03:22 UTC, marekdominiak commented on src/main/java/com/trainitek/backtothefuture/application/CompleteEnrollmentHandler.java
> +                .orElseThrow(() -> new IllegalArgumentException("Enrollment id=%s not found".formatted(enrollmentId)));
done

2023-10-20 03:22 UTC, marekdominiak commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +    def "Started enrollment can't be completed if time was tampered with"() {
I changed it to go forward.

2023-10-20 03:25 UTC, marekdominiak commented on src/test/groovy/com/trainitek/backtothefuture/domain/EnrollmentSpec.groovy
> +        thrown(IllegalArgumentException)
details added

2023-10-20 03:37 UTC, marekdominiak commented on src/main/java/com/trainitek/backtothefuture/domain/Enrollment.java
> +    public static Enrollment completedEnrollment(@NonNull User student, @NonNull User enroller, @NonNull Course course,
I think it was fine, lets discuss it when talking.

2023-10-20 03:37 UTC, marekdominiak commented on src/main/java/com/trainitek/backtothefuture/domain/Enrollment.java
> +    public static Enrollment completedEnrollment(@NonNull User student, @NonNull User enroller, @NonNull Course course,
I have removed both

2023-10-22 12:08 UTC, merged